# Generated by Django 2.1.3 on 2019-01-24 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('BOY', 'Boy'), ('GIRL', 'Girl')], default=None, max_length=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('size_system', models.CharField(choices=[('EU', 'EU'), ('UK', 'UK'), ('US', 'US')], default='EU', max_length=5)),
                ('child_status', models.CharField(choices=[('F', 'Full term'), ('P', 'Preemie'), ('Not born yet', 'Not born yet')], default='F', max_length=15)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('clothes_size_difference', models.IntegerField(blank=True, default=None, null=True)),
                ('shoe_size_difference', models.IntegerField(blank=True, default=None, null=True)),
                ('corrected_sizes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '32'), (1, '38'), (2, '44'), (3, '50'), (4, '56'), (5, '62'), (6, '68'), (7, '74'), (8, '80'), (9, '86'), (10, '92'), (11, '98'), (12, '104'), (13, '110'), (14, '116'), (15, '122'), (16, '128'), (17, '134'), (18, '140'), (19, '146'), (20, '152'), (21, '152')], default=None, max_length=55, null=True)),
                ('corrected_shoe_sizes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '15'), (1, '16'), (2, '17'), (3, '18'), (4, '19'), (5, '20'), (6, '21'), (7, '22'), (8, '23'), (9, '24'), (10, '25'), (11, '26'), (12, '26.5'), (13, '27'), (14, '28'), (15, '29'), (16, '30'), (17, '31'), (18, '32'), (19, '33'), (20, '34'), (21, '35'), (22, '36'), (23, '37'), (24, '38')], default=None, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('note', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('As good as new', 'As good as new'), ('Used but fine', 'Used but fine')], default='New', max_length=15)),
                ('sex', models.CharField(blank=True, choices=[('Boy', 'Boy'), ('Girl', 'Girl'), ('Unisex', 'Unisex')], default=None, max_length=6, null=True)),
                ('season', models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], default=None, max_length=7, null=True)),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Brown', 'Brown'), ('Grey', 'Grey')], default=None, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('amount', models.IntegerField(blank=True, default=1, null=True)),
                ('clothing_size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '32'), (1, '38'), (2, '44'), (3, '50'), (4, '56'), (5, '62'), (6, '68'), (7, '74'), (8, '80'), (9, '86'), (10, '92'), (11, '98'), (12, '104'), (13, '110'), (14, '116'), (15, '122'), (16, '128'), (17, '134'), (18, '140'), (19, '146'), (20, '152'), (21, '152')], default=None, max_length=55, null=True)),
                ('shoe_size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '15'), (1, '16'), (2, '17'), (3, '18'), (4, '19'), (5, '20'), (6, '21'), (7, '22'), (8, '23'), (9, '24'), (10, '25'), (11, '26'), (12, '26.5'), (13, '27'), (14, '28'), (15, '29'), (16, '30'), (17, '31'), (18, '32'), (19, '33'), (20, '34'), (21, '35'), (22, '36'), (23, '37'), (24, '38')], default=None, max_length=64, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Child')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Child')),
            ],
        ),
        migrations.CreateModel(
            name='SizeFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '32'), (1, '38'), (2, '44'), (3, '50'), (4, '56'), (5, '62'), (6, '68'), (7, '74'), (8, '80'), (9, '86'), (10, '92'), (11, '98'), (12, '104'), (13, '110'), (14, '116'), (15, '122'), (16, '128'), (17, '134'), (18, '140'), (19, '146'), (20, '152'), (21, '152')], default=None, max_length=55, null=True)),
                ('shoe_size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '15'), (1, '16'), (2, '17'), (3, '18'), (4, '19'), (5, '20'), (6, '21'), (7, '22'), (8, '23'), (9, '24'), (10, '25'), (11, '26'), (12, '26.5'), (13, '27'), (14, '28'), (15, '29'), (16, '30'), (17, '31'), (18, '32'), (19, '33'), (20, '34'), (21, '35'), (22, '36'), (23, '37'), (24, '38')], default=None, max_length=64, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Child')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Section'),
        ),
    ]
