# Generated by Django 2.1.3 on 2019-01-28 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='shared_with_me',
            field=models.ManyToManyField(blank=True, default=None, related_name='shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='shared_with_me_can_edit',
            field=models.ManyToManyField(blank=True, default=None, related_name='shared_with_me_can_edit', to=settings.AUTH_USER_MODEL),
        ),
    ]
