# Generated by Django 2.1.3 on 2019-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190128_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='shared_with_me',
            new_name='shared_with',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='shared_with_me_can_edit',
            new_name='shared_with_edit',
        ),
    ]
