# Generated by Django 2.1.3 on 2019-02-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190129_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSizeFilter',
            fields=[
                ('sizefilter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.SizeFilter')),
            ],
            bases=('home.sizefilter',),
        ),
    ]
